version: "3"

services:
  keycloak-postgresql:
    image: ${POSTGRES_IMAGE}
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ENABLE_TLS=no
    volumes:
      - postgresql_data:/bitnami/postgresql
    healthcheck:	
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]	
      interval: 10s	
      timeout: 5s	
      retries: 3	
      start_period: 60s	
    restart: always 
  keycloak:
    image: ${KEYCLOAK_IMAGE}
    ports:
      - ${KEYCLOAK_PORT}:8080
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_DATABASE_NAME=${POSTGRESQL_DATABASE}
      - KEYCLOAK_DATABASE_USER=${POSTGRESQL_USERNAME}
      - KEYCLOAK_DATABASE_PASSWORD=${POSTGRESQL_PASSWORD}
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_HOST=keycloak-postgresql
      - KEYCLOAK_ENABLE_HEALTH_ENDPOINTS=true
      - KEYCLOAK_ENABLE_STATISTICS=true
    depends_on:
      keycloak-postgresql:
        condition: service_healthy

volumes:
  postgresql_data:
