version: "3"

services:
  postgresql:
    image: bitnami/postgresql:13
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=bitnami_keycloak
      - POSTGRESQL_ENABLE_TLS=no
    volumes:
      - postgresql_data:/bitnami/postgresql
  keycloak:
    image: bitnami/keycloak:20.0.0
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
    depends_on:
      - postgresql


volumes:
  postgresql_data:
