version: "3"

services:
  proxy:
    image: ${NGINX_IMAGE}
    volumes:
      - type: bind
        source: ${NGINX_SOURCE}
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - ${NGINX_PORT}:80
      
