version: "3"
services:
  portainer:
    image: portainer/portainer-ce:linux-amd64
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9090:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: always
volumes:
  portainer_data:
