version: "3"
services:     
  vault:
    image: hashicorp/vault:1.16.0-rc2
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: test
    ports:
      - 8200:8200
    restart: always
    volumes:
      - vault-data:/vault/data 
volumes:
  vault-data:
