version: "3.0"
services:     
  vault:
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: test
    ports:
      - 8200:8200
    privileged: true
    restart: always
volumes:
  vault-data: